version: 0.0
os: linux
files:
  - source: target/sample-1.0-jar-with-dependencies.jar
    destination: /tmp

  - source: ~/app_scripts/run.sh
    destination: /tmp

hooks:
  ApplicationStart:
      - location: /tmp/app_scripts/run.sh
        timeout: 180