version: 0.0
os: linux
files:
  - source: target/sample-1.0-jar-with-dependencies.jar
    destination: /tmp

  - source: ./app_run.sh
    destination: /tmp

permissions:
    - object: ./app_run.sh
      owner: ec2-user
      mode: 777
      type:
        - file

hooks:
  AfterInstall:
      - location: ./app_run.sh
        timeout: 180

