version: 0.0
os: linux
files:
  - source: target/sample-1.0-jar-with-dependencies.jar
    destination: /tmp

  - source: app_run.sh
    destination: /tmp

hooks:
  ApplicationStart:
      - location: app_run.sh
        timeout: 180

permissions:
    - object: app_run.sh
      owner: root
      mode: 777
      type:
        - file