version: 0.0
os: linux
files:
  - source: target/sample-1.0.jar
    destination: /tmp

  - source: app_run.sh
    destination: /tmp

  - source: app_stop.sh
    destination: /tmp

permissions:
    - object: /tmp/app_run.sh
      owner: root
      mode: 777
      type:
        - file

    - object: /tmp/app_stop.sh
      owner: root
      mode: 777
      type:
        - file

hooks:
  ApplicationStop:
      - location: app_stop.sh
        timeout: 180
        runas: root
  ApplicationStart:
      - location: app_run.sh
        timeout: 180
        runas: root

